#!/usr/bin/env node
var opts = require('optimist');
var path = require('path');
var fs = require('fs');
var acorn = require('./lib/acorn.js');
var sd = require('showdown');
var showdown = new sd.converter();

var argv = opts.usage("Document a bunch of files.\nUsage $0")
               .demand(1)
               .describe("pre", "pre-processing JS file.")
               .describe("post", "post-processing JS file.")
               .describe("css", "CSS file to include")
               .default("out", "doc/")
               .describe("out", "where output should go").argv;


var outputDir = argv.out;
if (outputDir.charAt(outputDir.length - 1) != path.sep) {
  outputDir += path.sep;
}
var preProcess = argv.pre ? require(argv.pre) : function(x) { return x; };
var postProcess = argv.post ? require(argv.post) : function(x) { return x; };
var cssFile = argv.css || '';
var inputFiles = argv._;
var pendingDirExplorations = 0;
var pendingReads = 0;
var buffersToDocument = [];
var filesToWrite = 0;

var totalFilesParsed = 0, fileNamesWritten = [];
function copyFile(src, target, cb) {
  var readStream = fs.createReadStream(src),
      writeStream = fs.createWriteStream(target);
  readStream.pipe(writeStream);
  readStream.once('end', cb);
}

function readableSlug(str) {
  var rv = str.replace(/[-_^.]+/g, ' ').trim();
  rv = rv[0].toUpperCase() + rv.substring(1);
  return rv.replace(/([A-Z])([A-Z][a-z])/g, '$1 $2').replace(/([^A-Z])([A-Z])/g, '$1 $2').replace(/([A-Za-z])([^A-Za-z])/g, '$1 $2');
}

function documentFile(pathName) {
  pendingReads++;
  totalFilesParsed++;
  fs.readFile(pathName, function(err, b) {
    pendingReads--;
    if (err) {
      if (err.code == 'EISDIR') {
        pendingDirExplorations++;
        totalFilesParsed--;
        console.log(pathName + " is a directory, reading all files...");
        fs.readdir(pathName, function onFiles(err, files) {
          if (err) throw err;
          files.forEach(function(f) {
            if (path.extname(f) == '.js') {
              inputFiles.push(pathName + path.sep + f);
            }
          });
          pendingDirExplorations--;
        });
      } else {
        throw err;
      }
    } else {
      buffersToDocument.push({b: b, path: pathName});
    }
  });
}


function documentBuffer(b) {
  var jsInput = b.b.toString('utf8');
  var comments = [];
  function checkComment(isBlock, text, start, end) {
    if (isBlock && text[0] == '*') {
      var startingStar = /^\s*\*[\t ]?/gim;
      var docSlug = getDocSlug(jsInput, end);
      var c = {text: text.replace(startingStar, ''), start: start};
      if (docSlug) {
        c.slug = docSlug
      }
      comments.push(c);
    }
  };
  try {
    acorn.parse(jsInput, {onComment: checkComment});
  } catch (ex) {
    console.error("Error parsing file " + b.path);
    console.error(ex);
  }
  comments.sort(function(a, b) { return a.start - b.start });
  ensureDir(comments, b.path);
}

function ensureDir(commentList, pathName) {
  if (commentList.length) {
    filesToWrite += 2;
    fs.mkdir(outputDir, function(err, d) {
      outputDocs(commentList, pathName);
    });
  }
}

function outputDocs(commentList, pathName) {
  var outParts = [];
  for (var i = 0; i < commentList.length; i++) {
    var c = commentList[i];
    var t = '';
    if (c.slug) {
      t += '##' + ((c.slug[0] && c.slug[0] == c.slug[0].toLowerCase()) ? '# ' : ' ');
      t += c.slug + '\n';
    }
    t += c.text;
    outParts.push(t);
  }
  var fileName = path.basename(pathName, path.extname(pathName));
  var md = '# ' + readableSlug(fileName) + '\n' + outParts.join('\n\n');
  md = preProcess(md);
  var wrote = false;
  function onFW(err) {
    if (err) {
      console.error("Error writing docs for " + fileName);
    }
    if (wrote) {
      console.log("Finished writing docs for " + fileName);
    } else if (!err) {
      fileNamesWritten.push(fileName);
      wrote = true;
    }
    filesToWrite--;
  }
  fs.writeFile(outputDir + fileName + '.md', md, 'utf8', onFW);
  writeHtmlForMD(fileName, md, onFW);

}

function writeHtmlForMD(fileName, md, cb) {
  var html = '<!DOCTYPE html><html><head><title>' + readableSlug(fileName) + '</title><meta charset="utf8">';
  if (cssFile) {
    html += '<link href="style.css" rel="stylesheet" type="text/css" />';
  }
  html += '</head><body>' + postProcess(showdown.makeHtml(md)) + '</body></html>\n\n';
  fs.writeFile(outputDir + fileName + '.html', html, 'utf8', cb);
}



function getDocSlug(jsStr, pos) {
  var rv = '';
  var len = jsStr.length;
  var oldPos = pos;
  while (!rv && pos < len) {
    var newPos = jsStr.indexOf('\n', pos + 1);
    rv = jsStr.substring(pos, newPos);
    pos = newPos;
  }

  var replacers = [
    /function\s+(\w+)\(.*$/g,
    /.+?(\w+)\s*[:=]\s*function\s*\(.*$/g,
    /.*\w+\.prototype\.(\w+).*$/g
  ];

  var haveReplaced = false, i = replacers.length, lastRV = rv;
  while (i-- > 0 && !haveReplaced) {
    lastRV = rv;
    rv = rv.replace(replacers[i], '$1');
    haveReplaced = (rv != lastRV);
  }
  return haveReplaced ? rv.trim() : '';
}



function handleCSS(cb) {
  if (cssFile) {
    fs.mkdir(outputDir, function(err, d) {
      copyFile(cssFile, outputDir + 'style.css', function(err) {
        handleReadme();
        console.log("Copied CSS file");
      });
    });
  } else {
    process.nextTick(handleReadme);
  }
}


function handleReadme() {
  fs.readFile(outputDir + 'readme.md', function(err, buffer) {
    if (!err) {
      fileNamesWritten.sort();
      fileNamesWritten.unshift('readme');
      writeHtmlForMD('readme', buffer.toString('utf8'), handleStructure);
    }
  });
}

function handleStructure() {
  var linkHTML = '<ul><li>' + fileNamesWritten.map(function(x) { return '<a target="helpshown" href="' + x + '.html">' + readableSlug(x) + '</a>'; }).join('</li>\n<li>') + '</li></ul>';
  var html = '<!DOCTYPE html><html>\n<head><title>File list</title><meta charset="utf8"></head>\n<body>\n';
  html += linkHTML + '</body></html>\n\n';
  var filelistWritten = false;
  fs.writeFile(outputDir + 'filelist.html', html, function(err) {
    if (err) {
      console.error("An error occurred writing the file list file!");
    }
    filelistWritten = true;
    maybeFinish();
  });

  html = '<!DOCTYPE html><html>\n<head><title>Index</title><meta charset="utf8"></head>\n';
  html += '<frameset cols="200px,*"><frame src="filelist.html" name="toc" />\n<frame name="helpshown" src="' + fileNamesWritten[0] + '.html" /></frameset>\n</html>\n\n';
  var indexWritten = false;
  fs.writeFile(outputDir + 'index.html', html, function(err) {
    if (err) {
      console.error("An error occurred writing the index file!");
    }
    indexWritten = true;
    maybeFinish();
  });

  function maybeFinish() {
    if (filelistWritten && indexWritten) {
      var readmeIndex = fileNamesWritten.indexOf('readme');
      if (readmeIndex != -1) {
        fileNamesWritten.splice(readmeIndex, 1);
      }
      finish();
    }
  }
}

function finish() {
  console.log("Finished, wrote documentation for " + fileNamesWritten.length + " out of " + totalFilesParsed + " files.");
}


function eventLoop() {
  var pendingStuff = pendingReads + pendingDirExplorations + inputFiles.length + buffersToDocument.length + filesToWrite;
  if (pendingStuff != 0) {
    process.nextTick(eventLoop);
  } else {
    handleCSS();
  }

  if (inputFiles.length != 0) {
    documentFile(inputFiles.shift());
  }
  if (buffersToDocument.length != 0) {
    documentBuffer(buffersToDocument.shift());
  }
}

process.nextTick(eventLoop)

